### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by LeoGil** [LeoGil/plante_facil#1]
- [x] Retirar os bug dos textos
- [ ] Tela de recuperar senha
- [x] *ADMINISTRATIVO* Dashboard
- [x] *ADMINISTRATIVO* Cadastro de produtos
- [x] *ADMINISTRATIVO* Cadastro de cupons
- [x] *ADMINISTRATIVO* Cadastro de usuarios
- [ ] *INICIAL* Elaborar os textos
- [ ] *EXTRA* Lista de compras
- [ ] *EXTRA* Cadastro de cupons
